apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  namespace: project1
spec:
  selector:
    matchLabels:
      app: httpd
  replicas: 2
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: image-registry.openshift-image-registry.svc:5000/openshift/httpd:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always  
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities: 
              drop: 
              - ALL
            seccompProfile:
             type: "RuntimeDefault"